// Placeholder courses for testing and fallback
export const placeholderCourses = [
  {
    id: 1,
    title: "تعلم القرآن الكريم - المستوى الأول",
    instructor: "الشيخ محمد العريفي",
    description:
      "دورة شاملة لتعلم تلاوة القرآن الكريم بالتجويد والأحكام الأساسية. مناسبة للمبتدئين.",
    duration: "12 ساعة",
    lessonsCount: 24,
    level: "مبتدئ",
    category: "القرآن الكريم",
    thumbnail: "https://i.ytimg.com/vi/Dd7FixvoKBw/maxresdefault.jpg",
    isFeatured: true,
    progress: 0,
  },
  {
    id: 2,
    title: "السيرة النبوية الشريفة",
    instructor: "د. طارق السويدان",
    description:
      "رحلة شاملة في حياة النبي محمد ﷺ من الميلاد حتى الوفاة، مع الدروس المستفادة.",
    duration: "20 ساعة",
    lessonsCount: 40,
    level: "متوسط",
    category: "السيرة النبوية",
    thumbnail: "https://i.ytimg.com/vi/COqVxLf9MMI/maxresdefault.jpg",
    isFeatured: true,
    progress: 0,
  },
  {
    id: 3,
    title: "أصول الفقه الإسلامي",
    instructor: "د. محمد العوضي",
    description:
      "دراسة معمقة في أصول الفقه ومصادر التشريع الإسلامي والقواعد الفقهية.",
    duration: "15 ساعة",
    lessonsCount: 30,
    level: "متقدم",
    category: "الفقه الإسلامي",
    thumbnail: "https://i.ytimg.com/vi/vqZLNUhf1o8/maxresdefault.jpg",
    isFeatured: true,
    progress: 0,
  },
  {
    id: 4,
    title: "تفسير جزء عمّ",
    instructor: "الشيخ نابل العوضي",
    description:
      "شرح مفصل وميسر لسور جزء عمّ مع بيان المعاني والأحكام والفوائد.",
    duration: "8 ساعات",
    lessonsCount: 20,
    level: "مبتدئ",
    category: "التفسير",
    thumbnail: "https://i.ytimg.com/vi/afCH36zmTHs/maxresdefault.jpg",
    isFeatured: false,
    progress: 35,
  },
  {
    id: 5,
    title: "الأذكار والأدعية اليومية",
    instructor: "الشيخ محمد حسان",
    description:
      "تعلم الأذكار والأدعية الواردة عن النبي ﷺ في مختلف الأوقات والأحوال.",
    duration: "6 ساعات",
    lessonsCount: 15,
    level: "مبتدئ",
    category: "العبادات",
    thumbnail: "https://i.ytimg.com/vi/tN1FiQGy5ww/maxresdefault.jpg",
    isFeatured: false,
    progress: 0,
  },
  {
    id: 6,
    title: "العقيدة الإسلامية الصحيحة",
    instructor: "د. عائض القرني",
    description:
      "دراسة شاملة للعقيدة الإسلامية الصحيحة وفق منهج أهل السنة والجماعة.",
    duration: "18 ساعة",
    lessonsCount: 35,
    level: "متوسط",
    category: "العقيدة",
    thumbnail: "https://i.ytimg.com/vi/qx5wQt3qlNs/maxresdefault.jpg",
    isFeatured: false,
    progress: 60,
  },
];
